### ISSUE TITLE
Match returned AMZN item with Walmart UPC

### ISSUE THREAD

**Issue by sulaimonlasisi** [sulaimonlasisi/clearance-app#12]
At the moment, once a UPC goes into AMZN, it doesn't return a UPC, it only returns ASIN. We need to be able to keep the UPC around to match it with the walmart item that was queried for correct analysis

**Comment by danfstucky** [comment]
Added functionality for returning an array of paired Amazon and Walmart products. Now they can be easily compared with one another. 
Pull Request - https://github.com/sulaimonlasisi/clearance-app/pull/14
